version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
